package com.baishop.entity.shop;

import java.io.Serializable;

public class ShopType implements Serializable {

	private static final long serialVersionUID = 5388588950832582278L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_shop_type.type_id
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    private Integer typeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_shop_type.type_parent
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    private Integer typeParent;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_shop_type.type_path
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    private String typePath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_shop_type.type_name
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    private String typeName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_shop_type.type_logo
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    private String typeLogo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_shop_type.type_desc
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    private String typeDesc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_shop_type.type_id
     *
     * @return the value of bai_shop_type.type_id
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_shop_type.type_id
     *
     * @param typeId the value for bai_shop_type.type_id
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_shop_type.type_parent
     *
     * @return the value of bai_shop_type.type_parent
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public Integer getTypeParent() {
        return typeParent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_shop_type.type_parent
     *
     * @param typeParent the value for bai_shop_type.type_parent
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public void setTypeParent(Integer typeParent) {
        this.typeParent = typeParent;
    }

    public String getTypePath() {
		return typePath;
	}

	public void setTypePath(String typePath) {
		this.typePath = typePath;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_shop_type.type_name
     *
     * @return the value of bai_shop_type.type_name
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_shop_type.type_name
     *
     * @param typeName the value for bai_shop_type.type_name
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_shop_type.type_logo
     *
     * @return the value of bai_shop_type.type_logo
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public String getTypeLogo() {
        return typeLogo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_shop_type.type_logo
     *
     * @param typeLogo the value for bai_shop_type.type_logo
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public void setTypeLogo(String typeLogo) {
        this.typeLogo = typeLogo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_shop_type.type_desc
     *
     * @return the value of bai_shop_type.type_desc
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_shop_type.type_desc
     *
     * @param typeDesc the value for bai_shop_type.type_desc
     *
     * @ibatorgenerated Thu Oct 13 18:14:44 CST 2011
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }
}