package com.baishop.entity.ass;

import java.io.Serializable;

public class AdminsDepts implements Serializable {
	
	private static final long serialVersionUID = -4014335898008357899L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins_depts.dept_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    private Integer deptId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins_depts.user_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    private Integer userId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins_depts.dept_id
     *
     * @return the value of bai_admins_depts.dept_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins_depts.dept_id
     *
     * @param deptId the value for bai_admins_depts.dept_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins_depts.user_id
     *
     * @return the value of bai_admins_depts.user_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins_depts.user_id
     *
     * @param userId the value for bai_admins_depts.user_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}