package com.baishop.entity.ass;

import java.io.Serializable;

public class AdminsModules implements Serializable {

	private static final long serialVersionUID = -514087846786714697L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins_modules.module_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    private Integer moduleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins_modules.user_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    private Integer userId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins_modules.module_id
     *
     * @return the value of bai_admins_modules.module_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins_modules.module_id
     *
     * @param moduleId the value for bai_admins_modules.module_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins_modules.user_id
     *
     * @return the value of bai_admins_modules.user_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins_modules.user_id
     *
     * @param userId the value for bai_admins_modules.user_id
     *
     * @ibatorgenerated Thu Nov 03 18:04:39 CST 2011
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}