package com.baishop.entity.ass;

import java.io.Serializable;

public class City implements Serializable {

	private static final long serialVersionUID = 1128915453717385474L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_city.city_id
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    private Integer cityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_city.city_code
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    private String cityCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_city.city_name
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    private String cityName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_city.city_pinyin
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    private String cityPinyin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_city.city_parent_id
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    private Integer cityPid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_city.city_remark
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    private String cityRemark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_city.city_id
     *
     * @return the value of bai_city.city_id
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_city.city_id
     *
     * @param cityId the value for bai_city.city_id
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_city.city_code
     *
     * @return the value of bai_city.city_code
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_city.city_code
     *
     * @param cityCode the value for bai_city.city_code
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_city.city_name
     *
     * @return the value of bai_city.city_name
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_city.city_name
     *
     * @param cityName the value for bai_city.city_name
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_city.city_pinyin
     *
     * @return the value of bai_city.city_pinyin
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public String getCityPinyin() {
        return cityPinyin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_city.city_pinyin
     *
     * @param cityPinyin the value for bai_city.city_pinyin
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public void setCityPinyin(String cityPinyin) {
        this.cityPinyin = cityPinyin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_city.city_parent_id
     *
     * @return the value of bai_city.city_parent_id
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public Integer getCityPid() {
        return cityPid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_city.city_parent_id
     *
     * @param cityPid the value for bai_city.city_parent_id
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public void setCityPid(Integer cityPid) {
        this.cityPid = cityPid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_city.city_remark
     *
     * @return the value of bai_city.city_remark
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public String getCityRemark() {
        return cityRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_city.city_remark
     *
     * @param cityRemark the value for bai_city.city_remark
     *
     * @ibatorgenerated Sat Oct 08 15:11:00 CST 2011
     */
    public void setCityRemark(String cityRemark) {
        this.cityRemark = cityRemark;
    }
}