package com.baishop.entity.ass;

import java.io.Serializable;

public class Enums implements Serializable {

	private static final long serialVersionUID = -2874120736026538574L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_id
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    private Integer enumsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_type
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    private String enumsType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_name
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    private String enumsKey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_value
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    private String enumsValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_remark
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    private String enumsRemark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_id
     *
     * @return the value of bai_enums.enums_id
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public Integer getEnumsId() {
        return enumsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_id
     *
     * @param enumsId the value for bai_enums.enums_id
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public void setEnumsId(Integer enumsId) {
        this.enumsId = enumsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_type
     *
     * @return the value of bai_enums.enums_type
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public String getEnumsType() {
        return enumsType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_type
     *
     * @param enumsType the value for bai_enums.enums_type
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public void setEnumsType(String enumsType) {
        this.enumsType = enumsType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_name
     *
     * @return the value of bai_enums.enums_name
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public String getEnumsKey() {
        return enumsKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_name
     *
     * @param enumsKey the value for bai_enums.enums_name
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public void setEnumsKey(String enumsKey) {
        this.enumsKey = enumsKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_value
     *
     * @return the value of bai_enums.enums_value
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public String getEnumsValue() {
        return enumsValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_value
     *
     * @param enumsValue the value for bai_enums.enums_value
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public void setEnumsValue(String enumsValue) {
        this.enumsValue = enumsValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_remark
     *
     * @return the value of bai_enums.enums_remark
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public String getEnumsRemark() {
        return enumsRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_remark
     *
     * @param enumsRemark the value for bai_enums.enums_remark
     *
     * @ibatorgenerated Sat Apr 30 20:30:24 CST 2011
     */
    public void setEnumsRemark(String enumsRemark) {
        this.enumsRemark = enumsRemark;
    }
}