package com.baishop.entity.ass;

import java.io.Serializable;

public class Params implements Serializable {

	private static final long serialVersionUID = 6205694333619657345L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_params.params_id
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    private Integer paramsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_params.params_name
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    private String paramsName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_params.params_value
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    private String paramsValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_params.params_remark
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    private String paramsRemark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_params.params_id
     *
     * @return the value of bai_params.params_id
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public Integer getParamsId() {
        return paramsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_params.params_id
     *
     * @param paramsId the value for bai_params.params_id
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public void setParamsId(Integer paramsId) {
        this.paramsId = paramsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_params.params_name
     *
     * @return the value of bai_params.params_name
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public String getParamsName() {
        return paramsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_params.params_name
     *
     * @param paramsName the value for bai_params.params_name
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public void setParamsName(String paramsName) {
        this.paramsName = paramsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_params.params_value
     *
     * @return the value of bai_params.params_value
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public String getParamsValue() {
        return paramsValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_params.params_value
     *
     * @param paramsValue the value for bai_params.params_value
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public void setParamsValue(String paramsValue) {
        this.paramsValue = paramsValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_params.params_remark
     *
     * @return the value of bai_params.params_remark
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public String getParamsRemark() {
        return paramsRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_params.params_remark
     *
     * @param paramsRemark the value for bai_params.params_remark
     *
     * @ibatorgenerated Sat Apr 30 20:34:51 CST 2011
     */
    public void setParamsRemark(String paramsRemark) {
        this.paramsRemark = paramsRemark;
    }
}