package com.baishop.entity.ass;

import java.io.Serializable;

public class RemoteAuths implements Serializable {
	
	private static final long serialVersionUID = 641763647657562726L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_remote_auths.id
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_remote_auths.user
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    private String user;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_remote_auths.password
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_remote_auths.provide
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    private String provide;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_remote_auths.auths
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    private String auths;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_remote_auths.id
     *
     * @return the value of bai_remote_auths.id
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_remote_auths.id
     *
     * @param id the value for bai_remote_auths.id
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_remote_auths.user
     *
     * @return the value of bai_remote_auths.user
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_remote_auths.user
     *
     * @param user the value for bai_remote_auths.user
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_remote_auths.password
     *
     * @return the value of bai_remote_auths.password
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_remote_auths.password
     *
     * @param password the value for bai_remote_auths.password
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_remote_auths.provide
     *
     * @return the value of bai_remote_auths.provide
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public String getProvide() {
        return provide;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_remote_auths.provide
     *
     * @param provide the value for bai_remote_auths.provide
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public void setProvide(String provide) {
        this.provide = provide;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_remote_auths.auths
     *
     * @return the value of bai_remote_auths.auths
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public String getAuths() {
        return auths;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_remote_auths.auths
     *
     * @param auths the value for bai_remote_auths.auths
     *
     * @ibatorgenerated Mon Mar 26 18:28:55 CST 2012
     */
    public void setAuths(String auths) {
        this.auths = auths;
    }
}