package com.baishop.entity.ass;

import java.io.Serializable;
import java.util.List;

public class Roles implements Serializable {
	
	private static final long serialVersionUID = -8537787519039273673L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.role_id
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.rolePid
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private Integer rolePid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.role_name
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private String roleName;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.role_type
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private String roleType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.role_desc
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private String roleDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.sort
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private Integer sort;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column kd6_roles.leaf
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    private Integer leaf;
    
    /**
     * 模块列表
     */
    private List<Modules> modules;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kd6_roles.role_id
     *
     * @return the value of kd6_roles.role_id
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kd6_roles.role_id
     *
     * @param roleId the value for kd6_roles.role_id
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

	public Integer getRolePid() {
		return rolePid;
	}

	public void setRolePid(Integer rolePid) {
		this.rolePid = rolePid;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kd6_roles.role_name
     *
     * @return the value of kd6_roles.role_name
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kd6_roles.role_name
     *
     * @param roleName the value for kd6_roles.role_name
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kd6_roles.role_type
     *
     * @return the value of kd6_roles.role_type
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public String getRoleType() {
		return roleType;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kd6_roles.role_type
     *
     * @param roleName the value for kd6_roles.role_type
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kd6_roles.role_desc
     *
     * @return the value of kd6_roles.role_desc
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kd6_roles.role_desc
     *
     * @param roleDesc the value for kd6_roles.role_desc
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column kd6_roles.sort
     *
     * @return the value of kd6_roles.sort
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column kd6_roles.sort
     *
     * @param sort the value for kd6_roles.sort
     *
     * @ibatorgenerated Thu Nov 03 17:22:01 CST 2011
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

	public Integer getLeaf() {
		return leaf;
	}

	public void setLeaf(Integer leaf) {
		this.leaf = leaf;
	}

	public List<Modules> getModules() {
		return modules;
	}

	public void setModules(List<Modules> modules) {
		this.modules = modules;
	}
}