package com.baishop.entity.ass;

import java.io.Serializable;
import java.util.Date;

public class Syslog implements Serializable {
	
	private static final long serialVersionUID = 3061355441288651845L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.id
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.user
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private String user;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.source
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private Byte source;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.type
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.method
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private String method;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.args
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private String args;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.description
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.exec_time
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    private Date date;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.id
     *
     * @return the value of syslog.id
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.id
     *
     * @param id the value for syslog.id
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.user
     *
     * @return the value of syslog.user
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.user
     *
     * @param user the value for syslog.user
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.source
     *
     * @return the value of syslog.source
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.source
     *
     * @param source the value for syslog.source
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.type
     *
     * @return the value of syslog.type
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.type
     *
     * @param type the value for syslog.type
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.method
     *
     * @return the value of syslog.method
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.method
     *
     * @param method the value for syslog.method
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.args
     *
     * @return the value of syslog.args
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.args
     *
     * @param args the value for syslog.args
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setArgs(String args) {
        this.args = args;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.description
     *
     * @return the value of syslog.description
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.description
     *
     * @param description the value for syslog.description
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.exec_time
     *
     * @return the value of syslog.exec_time
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.exec_time
     *
     * @param execTime the value for syslog.exec_time
     *
     * @ibatorgenerated Tue Mar 13 10:56:08 CST 2012
     */
    public void setDate(Date date) {
        this.date = date;
    }
}