package com.baishop.entity.ass;

import java.util.Date;

public class Syslog {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.id
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.source
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private Byte source;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.signature
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private String signature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.args
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private String args;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.result
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private String result;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.description
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.exec_time
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private Long execTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column syslog.create_time
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    private Date createTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.id
     *
     * @return the value of syslog.id
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.id
     *
     * @param id the value for syslog.id
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.source
     *
     * @return the value of syslog.source
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.source
     *
     * @param source the value for syslog.source
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.signature
     *
     * @return the value of syslog.signature
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.signature
     *
     * @param signature the value for syslog.signature
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.args
     *
     * @return the value of syslog.args
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.args
     *
     * @param args the value for syslog.args
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setArgs(String args) {
        this.args = args;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.result
     *
     * @return the value of syslog.result
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.result
     *
     * @param result the value for syslog.result
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.description
     *
     * @return the value of syslog.description
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.description
     *
     * @param description the value for syslog.description
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.exec_time
     *
     * @return the value of syslog.exec_time
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public Long getExecTime() {
        return execTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.exec_time
     *
     * @param execTime the value for syslog.exec_time
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setExecTime(Long execTime) {
        this.execTime = execTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column syslog.create_time
     *
     * @return the value of syslog.create_time
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column syslog.create_time
     *
     * @param createTime the value for syslog.create_time
     *
     * @ibatorgenerated Thu Aug 16 16:36:28 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}