package com.baishop.entity.sale;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrderGoods implements Serializable {

	private static final long serialVersionUID = 3750845604286043422L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.goods_id
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private Long goodsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.order_id
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private Long orderId;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.goods_name
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private String goodsName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.goods_sn
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private String goodsSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.goods_number
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private Integer goodsNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.market_price
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.shop_price
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private BigDecimal shopPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.goods_attr
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private String goodsAttr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.is_real
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private Byte isReal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.is_real_send
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private Byte isRealSend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_goods.is_gift
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    private Byte isGift;
    
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.goods_id
     *
     * @return the value of bai_order_goods.goods_id
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.goods_id
     *
     * @param goodsId the value for bai_order_goods.goods_id
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.order_id
     *
     * @return the value of bai_order_goods.order_id
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.order_id
     *
     * @param orderId the value for bai_order_goods.order_id
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.goods_name
     *
     * @return the value of bai_order_goods.goods_name
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.goods_name
     *
     * @param goodsName the value for bai_order_goods.goods_name
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.goods_sn
     *
     * @return the value of bai_order_goods.goods_sn
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.goods_sn
     *
     * @param goodsSn the value for bai_order_goods.goods_sn
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.goods_number
     *
     * @return the value of bai_order_goods.goods_number
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.goods_number
     *
     * @param goodsNumber the value for bai_order_goods.goods_number
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.market_price
     *
     * @return the value of bai_order_goods.market_price
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.market_price
     *
     * @param marketPrice the value for bai_order_goods.market_price
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.shop_price
     *
     * @return the value of bai_order_goods.shop_price
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public BigDecimal getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.shop_price
     *
     * @param shopPrice the value for bai_order_goods.shop_price
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setShopPrice(BigDecimal shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.goods_attr
     *
     * @return the value of bai_order_goods.goods_attr
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.goods_attr
     *
     * @param goodsAttr the value for bai_order_goods.goods_attr
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.is_real
     *
     * @return the value of bai_order_goods.is_real
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public Byte getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.is_real
     *
     * @param isReal the value for bai_order_goods.is_real
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setIsReal(Byte isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.is_real_send
     *
     * @return the value of bai_order_goods.is_real_send
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public Byte getIsRealSend() {
        return isRealSend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.is_real_send
     *
     * @param isRealSend the value for bai_order_goods.is_real_send
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setIsRealSend(Byte isRealSend) {
        this.isRealSend = isRealSend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_goods.is_gift
     *
     * @return the value of bai_order_goods.is_gift
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public Byte getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_goods.is_gift
     *
     * @param isGift the value for bai_order_goods.is_gift
     *
     * @ibatorgenerated Sat Oct 15 14:17:18 CST 2011
     */
    public void setIsGift(Byte isGift) {
        this.isGift = isGift;
    }
}