package com.baishop.entity.sale;

import java.io.Serializable;
import java.util.Date;

public class OrderOption implements Serializable {

	private static final long serialVersionUID = 6506272793922401997L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.option_id
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private Long optionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.order_id
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private Long orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.action_user
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private String actionUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.order_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private Byte orderStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.shipping_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private Byte shippingStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.pay_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private Byte payStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.option_note
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private String optionNote;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_order_option.option_time
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    private Date optionTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.option_id
     *
     * @return the value of bai_order_option.option_id
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.option_id
     *
     * @param optionId the value for bai_order_option.option_id
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.order_id
     *
     * @return the value of bai_order_option.order_id
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.order_id
     *
     * @param orderId the value for bai_order_option.order_id
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.action_user
     *
     * @return the value of bai_order_option.action_user
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public String getActionUser() {
        return actionUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.action_user
     *
     * @param actionUser the value for bai_order_option.action_user
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setActionUser(String actionUser) {
        this.actionUser = actionUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.order_status
     *
     * @return the value of bai_order_option.order_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.order_status
     *
     * @param orderStatus the value for bai_order_option.order_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.shipping_status
     *
     * @return the value of bai_order_option.shipping_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public Byte getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.shipping_status
     *
     * @param shippingStatus the value for bai_order_option.shipping_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setShippingStatus(Byte shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.pay_status
     *
     * @return the value of bai_order_option.pay_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.pay_status
     *
     * @param payStatus the value for bai_order_option.pay_status
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.option_note
     *
     * @return the value of bai_order_option.option_note
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public String getOptionNote() {
        return optionNote;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.option_note
     *
     * @param optionNote the value for bai_order_option.option_note
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setOptionNote(String optionNote) {
        this.optionNote = optionNote;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_order_option.option_time
     *
     * @return the value of bai_order_option.option_time
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public Date getOptionTime() {
        return optionTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_order_option.option_time
     *
     * @param optionTime the value for bai_order_option.option_time
     *
     * @ibatorgenerated Sat Oct 15 10:48:10 CST 2011
     */
    public void setOptionTime(Date optionTime) {
        this.optionTime = optionTime;
    }
}