package com.baishop.entity.sale;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {

	private static final long serialVersionUID = -8030951151047984647L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.user_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.username
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.password
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.nickname
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String nickname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.email
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.mobile
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.telephone
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String telephone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.sex
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Byte sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.birthday
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Date birthday;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.pay_points
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Integer payPoints;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.rank_points
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Integer rankPoints;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.user_rank_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Integer userRankId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.address_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Integer addressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.reg_time
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Date regTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.last_update_time
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.last_login_ip
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String lastLoginIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.visit_count
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Long visitCount;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.isSubscribe
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Byte isSubscribe;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.enable
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private Byte enable;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_users.slaveDatabase
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    private String slaveDatabase;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.user_id
     *
     * @return the value of bai_users.user_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.user_id
     *
     * @param userId the value for bai_users.user_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.username
     *
     * @return the value of bai_users.username
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.username
     *
     * @param username the value for bai_users.username
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.password
     *
     * @return the value of bai_users.password
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.password
     *
     * @param password the value for bai_users.password
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.nickname
     *
     * @return the value of bai_users.nickname
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.nickname
     *
     * @param nickname the value for bai_users.nickname
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.email
     *
     * @return the value of bai_users.email
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.email
     *
     * @param email the value for bai_users.email
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.mobile
     *
     * @return the value of bai_users.mobile
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.mobile
     *
     * @param mobile the value for bai_users.mobile
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.telephone
     *
     * @return the value of bai_users.telephone
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.telephone
     *
     * @param telephone the value for bai_users.telephone
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.sex
     *
     * @return the value of bai_users.sex
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.sex
     *
     * @param sex the value for bai_users.sex
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.birthday
     *
     * @return the value of bai_users.birthday
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.birthday
     *
     * @param birthday the value for bai_users.birthday
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.pay_points
     *
     * @return the value of bai_users.pay_points
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Integer getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.pay_points
     *
     * @param payPoints the value for bai_users.pay_points
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setPayPoints(Integer payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.rank_points
     *
     * @return the value of bai_users.rank_points
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Integer getRankPoints() {
        return rankPoints;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.rank_points
     *
     * @param rankPoints the value for bai_users.rank_points
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setRankPoints(Integer rankPoints) {
        this.rankPoints = rankPoints;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.user_rank_id
     *
     * @return the value of bai_users.user_rank_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Integer getUserRankId() {
        return userRankId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.user_rank_id
     *
     * @param userRankId the value for bai_users.user_rank_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setUserRankId(Integer userRankId) {
        this.userRankId = userRankId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.address_id
     *
     * @return the value of bai_users.address_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.address_id
     *
     * @param addressId the value for bai_users.address_id
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.reg_time
     *
     * @return the value of bai_users.reg_time
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.reg_time
     *
     * @param regTime the value for bai_users.reg_time
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.last_update_time
     *
     * @return the value of bai_users.last_update_time
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.last_update_time
     *
     * @param lastUpdateTime the value for bai_users.last_update_time
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.last_login_ip
     *
     * @return the value of bai_users.last_login_ip
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.last_login_ip
     *
     * @param lastLoginIp the value for bai_users.last_login_ip
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.visit_count
     *
     * @return the value of bai_users.visit_count
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Long getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.visit_count
     *
     * @param visitCount the value for bai_users.visit_count
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setVisitCount(Long visitCount) {
        this.visitCount = visitCount;
    }

    public Byte getIsSubscribe() {
		return isSubscribe;
	}

	public void setIsSubscribe(Byte isSubscribe) {
		this.isSubscribe = isSubscribe;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_users.enable
     *
     * @return the value of bai_users.enable
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_users.enable
     *
     * @param enable the value for bai_users.enable
     *
     * @ibatorgenerated Sun Oct 09 13:46:32 CST 2011
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

	public String getSlaveDatabase() {
		return slaveDatabase;
	}

	public void setSlaveDatabase(String slaveDatabase) {
		this.slaveDatabase = slaveDatabase;
	}
}