package com.baishop.entity.goods;

import java.io.Serializable;

public class Category implements Serializable {

	private static final long serialVersionUID = 5354472685048257774L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_category.cate_id
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    private Integer cateId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_category.cate_parent
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    private Integer cateParent;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_category.cate_path
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    private String catePath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_category.cate_name
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    private String cateName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_category.cate_desc
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    private String cateDesc;
    

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_category.leaf
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private Byte leaf;
    
    private Integer sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_category.cate_id
     *
     * @return the value of bai_category.cate_id
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_category.cate_id
     *
     * @param cateId the value for bai_category.cate_id
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_category.cate_parent
     *
     * @return the value of bai_category.cate_parent
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public Integer getCateParent() {
        return cateParent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_category.cate_parent
     *
     * @param cateParent the value for bai_category.cate_parent
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public void setCateParent(Integer cateParent) {
        this.cateParent = cateParent;
    }

    public String getCatePath() {
		return catePath;
	}

	public void setCatePath(String catePath) {
		this.catePath = catePath;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_category.cate_name
     *
     * @return the value of bai_category.cate_name
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public String getCateName() {
        return cateName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_category.cate_name
     *
     * @param cateName the value for bai_category.cate_name
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public void setCateName(String cateName) {
        this.cateName = cateName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_category.cate_desc
     *
     * @return the value of bai_category.cate_desc
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public String getCateDesc() {
        return cateDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_category.cate_desc
     *
     * @param cateDesc the value for bai_category.cate_desc
     *
     * @ibatorgenerated Mon Oct 10 17:03:01 CST 2011
     */
    public void setCateDesc(String cateDesc) {
        this.cateDesc = cateDesc;
    }

	public Byte getLeaf() {
		return leaf;
	}

	public void setLeaf(Byte leaf) {
		this.leaf = leaf;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}
}