package com.baishop.entity.goods;

public class GoodsImgs {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_goods_imgs.imgs_id
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    private Long imgsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_goods_imgs.goods_id
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    private Long goodsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_goods_imgs.path
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    private String path;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_goods_imgs.sort
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    private Long sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_goods_imgs.imgs_id
     *
     * @return the value of bai_goods_imgs.imgs_id
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public Long getImgsId() {
        return imgsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_goods_imgs.imgs_id
     *
     * @param imgsId the value for bai_goods_imgs.imgs_id
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public void setImgsId(Long imgsId) {
        this.imgsId = imgsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_goods_imgs.goods_id
     *
     * @return the value of bai_goods_imgs.goods_id
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_goods_imgs.goods_id
     *
     * @param goodsId the value for bai_goods_imgs.goods_id
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_goods_imgs.path
     *
     * @return the value of bai_goods_imgs.path
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_goods_imgs.path
     *
     * @param path the value for bai_goods_imgs.path
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_goods_imgs.sort
     *
     * @return the value of bai_goods_imgs.sort
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_goods_imgs.sort
     *
     * @param sort the value for bai_goods_imgs.sort
     *
     * @ibatorgenerated Tue Dec 06 17:03:04 CST 2011
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }
}