package com.baishop.entity.goods;

import java.io.Serializable;

public class Properties implements Serializable {

	private static final long serialVersionUID = 3426582291809086866L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_properties.props_id
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    private Integer propsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_properties.cate_id
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    private Integer cateId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_properties.props_name
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    private String propsName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_properties.input_type
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    private Byte inputType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_properties.input_values
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    private Byte inputValues;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_properties.sort
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    private Integer sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_properties.props_id
     *
     * @return the value of bai_properties.props_id
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public Integer getPropsId() {
        return propsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_properties.props_id
     *
     * @param propsId the value for bai_properties.props_id
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public void setPropsId(Integer propsId) {
        this.propsId = propsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_properties.cate_id
     *
     * @return the value of bai_properties.cate_id
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_properties.cate_id
     *
     * @param cateId the value for bai_properties.cate_id
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_properties.props_name
     *
     * @return the value of bai_properties.props_name
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public String getPropsName() {
        return propsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_properties.props_name
     *
     * @param propsName the value for bai_properties.props_name
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public void setPropsName(String propsName) {
        this.propsName = propsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_properties.input_type
     *
     * @return the value of bai_properties.input_type
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public Byte getInputType() {
        return inputType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_properties.input_type
     *
     * @param inputType the value for bai_properties.input_type
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public void setInputType(Byte inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_properties.input_values
     *
     * @return the value of bai_properties.input_values
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public Byte getInputValues() {
        return inputValues;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_properties.input_values
     *
     * @param inputValues the value for bai_properties.input_values
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public void setInputValues(Byte inputValues) {
        this.inputValues = inputValues;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_properties.sort
     *
     * @return the value of bai_properties.sort
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_properties.sort
     *
     * @param sort the value for bai_properties.sort
     *
     * @ibatorgenerated Thu Oct 13 15:15:47 CST 2011
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}